export { default as CreateBearPage } from './CreateBear/CreateBear'
export { default as LoginPage } from './Login/Login'
export { default as MainPage } from './Main/Main'
export { default as LandingPage } from './Landing/Landing'
export { default as NotFoundPage } from './NotFound/NotFound'